backbone: resnet18

# COMMA
img_width: 320
img_height: 160

# DIPLECS
# img_width: 320
# img_height: 240

img_scale_factor: 32

# d_encoder: 512
# d_decoder: 128
d_model: 512

seq_l: 8
n_head: 4

lr: 1.0e-3
l2: 1.0e-4
bins: [-1.1, -0.3, -0.15, -0.05, 0.05, 0.15, 0.3, 1.1]

div_factor: 25
final_div_factor: 10
pct_start: 0.25
anneal: cos

batch_size: 32
epochs: 20
p: 0.5